### ISSUE TITLE
Open to large refactoring?

### ISSUE THREAD

**Issue by whackashoe** [traildb/traildb-cpp#5]
I'd like to do a large refactor of this which would create new files, rename a bunch, etc, would you be open to a pull request on that level?

**Comment by aimran** [comment]
Sounds like a plan. Lets talk more about what you were thinking (a bit more in detail). Thanks again for your contribution

**Comment by whackashoe** [comment]
Sure, so a lot would include using more C++11 features (move C-style arrays to c++ arrays among other things), using const everywhere it can be, renaming things to use normal C++ casing (lowercase & underscores), toss this all in some namespace. Really just a large assortment of minor changes

What we could do as well is even toss all of this into one .h file as its already just a header only lib anyways- that I think is pretty neat for ease of use, but somewhat subjective.

**Comment by aimran** [comment]
Awesome. I like it — this will be a great improvement

**Comment by whackashoe** [comment]
Sweet! OK I'll do pr when its ready. Thanks!
